### PR TITLE
[Easy] Update package.json to react 0.8.0-rc

### PR DESCRIPTION
**Pull request by pcottle**
Hey @brentvatne ! Love the demo of the animation API

Small suggestion here to update the package.json dependency to the react 0.8.0-rc release rather than an arbitrary commit on your fork.

I used the tar link but could switch to another way of marking the commit if necessary.

### CODE REVIEW

**Comment by pcottle** [comment]
One pro with this update is that the annoying babel logspew goes away:

screen shot 2015-07-12 at 8 04 59 am

but the con is that https://github.com/facebook/react-native/issues/1944 still spews:

```
[08:02:00] <END>   fs crawl (548ms)
TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:413:5)
    at /Users/pcottle/Dropbox (Personal)/wip/react-native-animated-demo-tinder/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/index.js:153:33
    at tryCallOne (/Users/pcottle/Dropbox (Personal)/wip/react-native-animated-demo-tinder/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/pcottle/Dropbox (Personal)/wip/react-native-animated-demo-tinder/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/pcottle/Dropbox (Personal)/wip/react-native-animated-demo-tinder/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
[08:02:03] <START> request:/src/js/init/index.ios.bundle
```

but that should be fixed eventually (a few PR out to fix it), and only happens once per load. and is harmless

**Comment by brentvatne** [comment]
Thanks man :) :+1:

This is live now so we could just use `"react-native": "0.8.0-rc"` but I'm not fussy so this works too

**Comment by brentvatne** [comment]
By the way, thanks for fpp, it's great :smile:

**Comment by pcottle** [comment]
> This is live now so we could just use "react-native": "0.8.0-rc" but I'm not fussy so this works too

Ahh! Good to know -- that's way cleaner. I'm not super fussy about this stuff either but `0.8.0-rc` is quite concise :+1: 

I had tried `facebook/react-native#0.8.0-rc` but got some random error -- probably should have spent 2 more minutes googling.

> By the way, thanks for fpp, it's great :smile:

Glad you like it! It's pretty much 100% in maintenance mode so I'm trying to scratch my GitHub itch in other ways now

**Comment by pcottle** [comment]
(oh and the shorter version is over in #3, no rush)

**Pull request merged**
